### ISSUE TITLE
[question] Bottom Link: Impressum Datenschutzerklarung?

### ISSUE THREAD

**Issue by clsource** [wireshell/wireshell#44]
In the bottom of the wireshell website is a link to
http://processwire-recipes.com/about/impressum-datenschutzerklarung/

as is in deutsch I cannot fully understand it, 
but its seems like a legal sort of thing.

my question is
is necessary for wireshell?

thanks :)

**Comment by marcus-herrmann** [comment]
I can feel you regarding your confusion, german "Impressum" law borders to insanity. The footer link was originially in wireshell.pw, hosted on a server in Cologne by a German citizen (me). Although the site's target group wasn't just Germans, but the whole world. But experiences with Impressum law lead me to the conclusion to be better save than sorry.

Maybe you know the following site, which is full of Frontend goodness and inspirational/cutting edge CSS stuff. Look in the footer. There is a impressum, because the people behind it are Germans. Target audiences do not matter. Lawmakers here in Germany just don't get the net.

Now wireshell.pw is not hosted in Cologne anymore, I guess. But try to explain the hosting situation to a German judge. I don't even want to come close to such an situation. I don't want any ridiculous trouble coming from an Open Source project.

Therefore, it's still included.

What are your thoughts on this @justonestep ? As a German you can feel my anxiety  ;)

**Comment by clsource** [comment]
We could put those legal text inside a section in LICENCE :+1:

**Comment by marcus-herrmann** [comment]
This idea is totally common sense. But:

I'm afraid this is like having no impressum at all. "Impressum" has to be immediately visible or at least labeled something like Impressum or Kontakt. 

Putting it into LICENCE would be "hidden".

**Comment by clsource** [comment]
In that case we should put
a new file named Impressum.md
with those texts inside the repo.

Then on the footer link to that file
instead the processwire recipies site.

:+1:

**Comment by marcus-herrmann** [comment]
Good idea.

**Comment by marcus-herrmann** [comment]
Now part of the static page.

**Comment by clsource** [comment]
@marcus-herrmann great work :+1: , its possible to have an english translation too? I know its only for germany legal stuff, but I think its a good idea to have an english version so anyone knows whats it is :+1:

**Comment by marcus-herrmann** [comment]
I'm afraid it would need a lawyer to translate this. It's about liability for content, links (!, see how messed up German internet law is), trademarks.
